name: dependent_multiselect_search_dropdown
description: A customizable Flutter widget for cascading, multi-select, dependent and searchable dropdowns with dynamic updates.
version: 1.2.1
repository: https://github.com/innoventix-solutions/dependent_multiselect_search_dropdown_
publisher: https://innoventixsolutions.com
keywords:
  - dropdown
  - cascading dropdown
  - multi-select
  - searchable dropdown
  - dependent dropdown
  - flutter package
  - dynamic dropdown
  - form dropdown
  - multiselect dropdown
  - multiselect searchable dropdown
  - flutter dropdown
  - muliselect with search dropdown
  - multi-select dropdown
  - multi-select searchable dropdown
  - search dropdown

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  material_color_utilities: ^0.11.1 # or the correct version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  # To add assets to your application, add an assets section, like this:
assets:
  - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
